.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. trollcoin_qt test_trollcoin_qt
clean: FORCE
	$(MAKE) -C .. trollcoin_qt_clean test_trollcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_trollcoin_qt_check
trollcoin-qt trollcoin-qt.exe: FORCE
	 $(MAKE) -C .. trollcoin_qt
